### ISSUE TITLE
USER STORY: Anonymous poll answer

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/love-running#2]
In order to **provide my feedback anonymously** as a **use**, I can **hide my information before submitting the response**

### Acceptance Criteria:

- Checkbox to hide or show personal information when submitting
- Personal information should be hidden when the answer is submitted with the button checked
- Personal information should appear when the answer is submitted with the button unchecked

### Tasks:

- [ ] Update the view: poll design (HTML and CSS) to include the checkbox and show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Test the functionality
